[features]
seeds = false
skip-lint = false
[programs.localnet]
arbitrary_cpi = "HvdkrQW4ZY6nJ9u3sqXQdkHeSChXQ8f3Sj3vJwaitut5"
callee_program = "C6J4ttv9YtPCqrtL563KZuqC4yvHtQ1YeUpfKYF5FwoY"
callee_program_fake = "9kQK8xVskuvF8e1NfThkKrfcVZu6HNiCWF2b9C9C7SXg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
