[features]
seeds = false
skip-lint = false
[programs.localnet]
owner_check = "BRAn5brMcPV69i6uH3jpaG9FcDEVYo5rGMyAPsMwzWEE"
clone = "A4eTQheZwwx7GRm441KfXnsK4ZCf3RDbx4Dxmv8p9a2z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
