[features]
seeds = false
skip-lint = false
[programs.localnet]
clone = "5SmitLhxfKa9F7FeW84veXYKWUfsxvujh7fGf1gTY6Ju"
owner_check = "Cft4eTTrt4sJU4Ar35rUQHx6PSXfJju3dixmvApzhWws"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
