[features]
seeds = false
skip-lint = false
[programs.localnet]
type_cosplay = "4EAyrs6uzEXvKb8DPEsQrmBTD4j3CUYdutGvjqBnBQh2"
type_cosplay_secure = "9yEqz9ERHNopkSsh9bhyCVEps74KN7pyiLbNXnVuHrRW"
type_cosplay_recommended = "5657x5XSmUukd1jfQLZ5C6W2r6gBKNaHv14xMdh8xFA4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
