[features]
seeds = false
skip-lint = false
[programs.localnet]
signer_authorization = "9xCciLpuCeYivkpFcNaW6doRQ3XfbbQ7G6cGitJij9vQ"
account_data_matching = "5JcpLgkgWp97fy6BBfNJfqTdfgJw2DntQx17NTajMCYq"
owner_check = "7rLYxDkCFsTkvPbbK6YiPi6SoqCxaSkRSbR5VDkUqv2Y"
type_cosplay = "AC8RLrKaWxnB3ksZH2kVCF2GLKavV2aSsZ9ExmhyG4v9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/johnliu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/type-cosplay.ts"
